version: 2.0
defaults: &defaults
  docker:
    - image: nervesproject/nerves_system_br:1.5.2

install_elixir: &install_elixir
  run:
    name: Install Elixir
    command: |
      wget https://github.com/elixir-lang/elixir/releases/download/v1.7.3/Precompiled.zip
      unzip -d /usr/local/elixir Precompiled.zip
      echo 'export PATH=/usr/local/elixir/bin:$PATH' >> $BASH_ENV

install_hex_archives: &install_hex_archives
  run:
    name: Install archives
    command: |
      cd /tmp
      mix local.hex --force
      mix local.rebar --force
      mix archive.install hex nerves_bootstrap "~> 1.2" --force

fetch_and_compile_deps: &fetch_and_compile_deps
  run:
    name: Fetch and compile Elixir dependencies
    command: |
      mix deps.get
      mix compile

install_arduino: &install_arduino
  run:
    name: Run setup script
    command: bash .circleci/setup-arduino.sh

install_slack_helpers: &install_slack_helpers
  run:
    name: Install Slack Helpers
    command: |
      wget https://gist.githubusercontent.com/ConnorRigby/03e722be4be70f8588f5ed74420e4eaa/raw/28a51d8f52ec7d569e8f7f20b83349816ddf63cf/slack_message.ex

install_ghr: &install_ghr
  run:
    name: Install ghr (Github Releases)
    command: |
      wget https://github.com/tcnksm/ghr/releases/download/v0.9.0/ghr_v0.9.0_linux_amd64.tar.gz
      tar xf ghr_v0.9.0_linux_amd64.tar.gz
      ln -sf ghr_v0.9.0_linux_amd64/ghr .
jobs:
  test_farmbot_os:
    <<: *defaults
    environment:
      MIX_ENV: test
      MIX_TARGET: host
      ELIXIR_VERSION: 1.7.3
      SKIP_ARDUINO_BUILD: 1
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          keys:
            - v5-fbos-host-test-dependency-cache-{{ checksum "mix.lock.host" }}
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap
      - run:
          name: Test Farmbot OS
          command: |
            mix deps.get
            mix compile
            mix test
      - save_cache:
          key: v5-fbos-host-test-dependency-cache-{{ checksum "mix.lock.host" }}
          paths:
            - _build/host
            - deps/host
  rpi3_firmware:
    <<: *defaults
    environment:
      MIX_ENV: prod
      MIX_TARGET: rpi3
      ELIXIR_VERSION: 1.7.3
    steps:
      - checkout
      - run git submodule update --init --recursive
      - restore_cache:
        keys:
          - v5-fbos-rpi3-prod-dependency-cache-{{ checksum "mix.lock.rpi3" }}
          - v5-fbos-host-test-dependency-cache-{{ checksum "mix.lock.host" }}
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap
      - run:
        name: Build Farmbot OS Firmware
        command: |
          mix deps.get
          mix firmware
          mix nerves_hub.firmware sign --key ${NERVES_HUB_ORG}
      - run:
          name: Create artifact dir
          command: mkdir -p /nerves/deploy/system/artifacts
      - run:
          name: Create artifacts
          command: |
            cp _build/rpi3/prod/nerves/images/farmbot.fw /nerves/deploy/system/artifacts/farmbot-${MIX_TARGET}-$(cat VERSION).fw
      - save_cache:
          key: v5-fbos-rpi3-prod-dependency-cache-{{ checksum "mix.lock.rpi3" }}
          paths:
            - _build/rpi3/
            - deps/rpi3
      - store_artifacts:
          path: /nerves/deploy/system/artifacts
          destination: images
      - save_cache:
          key: nerves/deploy/system-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
          paths:
            - "/nerves/deploy/system"
  deploy_stable_image:
    <<: *defaults
    environment:
      MIX_ENV: prod
      MIX_TARGET: rpi3
      ELIXIR_VERSION: 1.7.3
    steps:
      - checkout
      - run git submodule update --init --recursive
      - restore_cache:
          keys:
            - v5-fbos-rpi3-prod-dependency-cache-{{ checksum "mix.lock.rpi3" }}
            - v5-fbos-host-test-dependency-cache-{{ checksum "mix.lock.host" }}
            - nerves/deploy/system-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
      - run:
          name: Create Image file
          command: mix firmware.image /nerves/deploy/system/farmbot-${MIX_TARGET}-$(cat VERSION).img
      - <<: *install_ghr
      - run:
          command: grep -Pazo "(?s)(?<=# $(cat VERSION))[^#]+" CHANGELOG.md > RELEASE_NOTES
      - run:
          name: Publish Github Release
          command: ./ghr -t $GITHUB_TOKEN -u farmbot -r farmbot_os -recreate -prerelease -draft -delete -b "$(cat RELEASE_NOTES)" -c $(git rev-parse --verify HEAD) "v$(cat VERSION)" /nerves/deploy/system/
      - run:
          name: Publish to NervesHub
          command: mix nerves_hub.firmware publish --key ${NERVES_HUB_ORG}
  deploy_beta_image:
    <<: *defaults
    environment:
      MIX_ENV: prod
      MIX_TARGET: rpi3
      ELIXIR_VERSION: 1.7.3
    steps:
      - checkout
      - run git submodule update --init --recursive
      - restore_cache:
          keys:
            - v5-fbos-rpi3-prod-dependency-cache-{{ checksum "mix.lock.rpi3" }}
            - v5-fbos-host-test-dependency-cache-{{ checksum "mix.lock.host" }}
            - nerves/deploy/system-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
      - run:
          name: Create Image file
          command: mix firmware.image /nerves/deploy/system/farmbot-${MIX_TARGET}-$(cat VERSION).img
      - <<: *install_ghr
      - run:
          command: grep -Pazo "(?s)(?<=# $(cat VERSION))[^#]+" CHANGELOG.md > RELEASE_NOTES
      - run:
          name: Publish Github Release
          command: ./ghr -t $GITHUB_TOKEN -u farmbot -r farmbot_os -prerelease -recreate -prerelease -b "$(cat RELEASE_NOTES)" -c $(git rev-parse --verify HEAD) "v$(cat VERSION)" /nerves/deploy/system/
      - run:
          name: Publish to NervesHub
          command: mix nerves_hub.firmware publish --key ${NERVES_HUB_ORG} --deploy prod-beta

workflows:
  version: 2
  test:
    jobs:
      - test_farmbot_os:
          context: org-global
          filters:
            branches:
              ignore:
                - beta
                - master
  test_deploy_stable_prod:
    jobs:
      - rpi3_firmware:
          context: farmbot-production
          filters:
            branches:
              only:
                - master
      - deploy_stable_image:
          context: farmbot-production
          filters:
            branches:
              only:
                - master
          requires:
            - rpi3_firmware
  test_deploy_beta_prod:
    jobs:
      - rpi3_firmware:
          context: farmbot-production
          filters:
            branches:
              only:
                - beta
      - deploy_stable_image:
          context: farmbot-production
          filters:
            branches:
              only:
                - beta
          requires:
            - rpi3_firmware
  test_deploy_stable_staging:
    jobs:
      - rpi3_firmware:
          context: farmbot-staging
          filters:
            branches:
              only:
                - master
      - deploy_stable_image:
          context: farmbot-staging
          filters:
            branches:
              only:
                - master
          requires:
            - rpi3_firmware
  test_deploy_beta_staging:
    jobs:
      - rpi3_firmware:
          context: farmbot-staging
          filters:
            branches:
              only:
                - beta
      - deploy_stable_image:
          context: farmbot-staging
          filters:
            branches:
              only:
                - beta
          requires:
            - rpi3_firmware